[package]
name = "ozone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.3.0"
chumsky = "0.8.0"
colored = "2.0.0"
logos = "0.12.1"
num-bigint = "0.4.3"
radix_fmt = "1.0.0"
